name: Build after change

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Install requirements and run
        run: |
          .\Build.bat
      - name: Commit and Push
        continue-on-error: true
        run: |
          git config user.name Auto-updater
          git config user.email auto-updater@users.noreply.github.com
          git add .
          git commit -m 'Recompile'
          git push -f -u origin master